#%RAML 1.0 Library


types:
  ###############
  # Supplier Data Types:
  ###############
  

  supplierData: !include supplier-datatype.raml
  supplierResponseData: !include supplier-response-datatype.raml