#%RAML 1.0 DataType
properties:

  supplierId: 
    type: string
    required: true
    displayName: "Supplier ID"
    example: "123456789"
    description: "eKomerico Supplier ID"
  supplierName: 
    type: string
    required: true
    example: "Nombre o Razón Social del Proveedor."
    displayName: "Supplier Name"
    description: "Nombre o Razón Social del Proveedor"
  message:
    type: string
    required: true
    displayName: "Supplier Message"
    example: "Creado con éxito"
      