#%RAML 1.0 NamedExample
{
  "Comment_Data": "Test Data Mule",
  "Submit": true,
  "Locked_in_Workday": true,
  "Company_Reference": "11000",
  "Currency_Reference": "USD",
  "Customer_Reference": "PSCRM_200003760",
  "Sold_To_Customer_Reference": "PSCRM_200003760",
  "Bill_To_Address_Reference": "PSCRM_CONTACT_552225",
  "Bill_To_Contact_Reference": "PSCRM_CONTACT_552225",
  "Populate_with_Default_Bill_To_Contacts": false,
  "Invoice_Date": "",
  "From_Date": "",
  "To_Date": "",
  "Payment_Terms_Reference": "Net_30",
  "Payment_Type_Reference": "Check_(AR)",
  "Customer_Invoice_Type_Reference": "Digital_3_Installment",
  "On_Hold": false,
  "Is_Excluded_from_Dunning_Letter": false,
  "Memo": "Test Mule",
  "Customer_Invoice_Line_Reference_ID": "11000",
  "Intercompany_Affiliate_Reference": "",
  "Revenue_Category_Reference": "R0238",
  "Line_Item_Description": "BLI---",
  "Tax_Applicability_Reference": "GST_or_Sales_Nonrecoverable_Allocation",
  "Quantity": 0,
  "Unit_of_Measure_Reference": "CPM",
  "Unit_Cost": 0,
  "Extended_Amount": 0,
  "Customer_Invoice_Line_From_Date": "",
  "Customer_Invoice_Line_To_Date": "",
  "Customer_invoice_memo": "Test",
  "Cost_Center_Worktag_Reference_ID": "00010",
  "Custom_Organization_Worktag_Reference_ID": "0125",
  "Custom_Organization_Worktag_Reference_ID_1": "PT003",  
  "Custom_Worktag_4_ID": "ENT199246"
}